[core] rename vanguard
derailedapp/derailed pull request #15
Opened 2024-02-12 12:00 UTC by VincentRPS

closes #13.

2024-02-12 12:57 UTC, elenakrittik approved these changes
I am probably supposed to add some useful notes and raise some important questions, but i don't even remember what vanguard is so here are my two absolutely useless nitpicks instead, you're welcome.

2024-02-12 12:57 UTC, elenakrittik commented on pnpm-workspace.yaml
>    - "shared/**"
```suggestion
  - "shared/**"

```

2024-02-12 12:57 UTC, elenakrittik commented on CHANGELOG.md
And introduce confusion with Diesel ORM? Maybe just "frontend" or something? Not all things need to have a name

2024-02-12 13:00 UTC, THEGOLDENPRO commented on CHANGELOG.md
I don't mind diesel but umm I agree with you.

2024-02-12 13:00 UTC, train9 commented on CHANGELOG.md
that could also become confusing since the `app` can also be considered part of Derailed's frontend, so the only way I've thought to circumnavigate that is to give it a unique name.

2024-02-12 13:02 UTC, THEGOLDENPRO commented
I will approve when I'm on desktop but wait for @spifory to approve too.

2024-02-12 13:03 UTC, elenakrittik commented on CHANGELOG.md
I mean, in the end it doesn't really matter given it's an internal name (unless we actually use Diesel ORM, then this name would become problematic), so as i said it's all just tiny rants and nitpicks.

2024-02-12 13:05 UTC, THEGOLDENPRO commented on CHANGELOG.md
Yeah I see

2024-02-12 13:24 UTC, steamweaver commented
Hello! I am your friendly Train Conductor here in station Derailed to inform you that you must sign our [Contributor License Agreement](https://gist.github.com/VincentRPS/3b0f267edfa23e365b03b8bbc2f0cc6e) before preceding. Once you've finished reading, and agree to everything there, comment 'I have read the CLA Document and I hereby sign the CLA' so we can merge your PR!

Go Fix Some Code, Train Conductor
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **1** out of **2** committers have signed the CLA.<br/>:white_check_mark: (VincentRPS)[https://github.com/VincentRPS]<br/>:x: @steamweaver<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

2024-02-12 13:29 UTC, VincentRPS commented on CHANGELOG.md
> And introduce confusion with Diesel ORM? Maybe just "frontend" or something? Not all things need to have a name

Here, final name I'm gonna be doing, "Hazel."

2024-02-12 19:34 UTC, THEGOLDENPRO approved these changes

2024-02-12 20:46 UTC, spifory requested changes

2024-02-12 20:46 UTC, spifory commented on CHANGELOG.md
> +Renames Vanguard to Hazel to prevent confusion with Riot Games' Anti-Cheat Vanguard.
Might be incorrect but I'm not sure if anti-cheat needs to be capitalised

2024-02-12 21:06 UTC, elenakrittik commented on hazel/app/layout.tsx
> +  title: "Derailed",
Probably because "Vanguard" (and the new "Hazel") are hust internal names. It is not particularly useful (i.e. is useless) for end users

2024-02-12 21:17 UTC, THEGOLDENPRO commented on CHANGELOG.md
> +Renames Vanguard to Hazel to prevent confusion with Riot Games' Anti-Cheat Vanguard.
yeah I don't think it needs to be

2024-02-13 09:16 UTC, spifory commented
Overall looks like there's no traces of vanguard written so I suppose it's fine (after fixing resolving my earlier review)
![image](https://github.com/derailedapp/derailed/assets/80943664/15bbb8d9-67af-49c7-9e8f-075a17b5782d)

2024-02-13 11:34 UTC, merged